name: NightlyBuild

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Check out repository
                uses: actions/checkout@v2

            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 21

            -   name: Extra Gradle cache
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches/fast-remapper
                        ~/.gradle/caches/forge_gradle
                    key: ${{ runner.os }}-extra-${{ hashFiles('~/.gradle/caches/fast-remapper', '~/.gradle/caches/forge_gradle') }}
                    restore-keys: |
                        ${{ runner.os }}-extra-
            -   name: Gradle assemble
                uses: burrunan/gradle-cache-action@v1
                env:
                    OVERRIDE_VERSION: ${{ env.modVer }}
                with:
                    concurrent: true
                    arguments: --build-cache assemble

            -   name: Copy jar
                env:
                    modVer: ${{ env.modVer }}
                run: |
                    cp build/libs/TrollHack-$modVer.jar TrollHack-$modVer.jar

            -   name: Upload jar
                uses: actions/upload-artifact@v2
                with:
                    name: nightly-build
                    path: TrollHack-${{ env.modVer }}.jar